parameters:
    # Constant authentication execution time in seconds (float). Blocks timing attacks.
    # Must be larger than expected real execution time, with a good margin.
    # If set to zero, constant time authentication is disabled. Do not do this on production environments.
    ibexa.security.authentication.constant_auth_time: !php/const eZ\Bundle\EzPublishCoreBundle\DependencyInjection\Compiler\SecurityPass::CONSTANT_AUTH_TIME_DEFAULT

services:
    ezpublish.security.user_provider.username:
        class: eZ\Publish\Core\MVC\Symfony\Security\User\UsernameProvider
        arguments:
            - '@eZ\Publish\API\Repository\UserService'
            - '@eZ\Publish\API\Repository\PermissionResolver'

    ezpublish.security.user_provider.email:
        class: eZ\Publish\Core\MVC\Symfony\Security\User\EmailProvider
        arguments:
            - '@eZ\Publish\API\Repository\UserService'
            - '@eZ\Publish\API\Repository\PermissionResolver'

    eZ\Publish\Core\MVC\Symfony\Security\UserChecker:
        arguments:
            - '@eZ\Publish\API\Repository\UserService'

    ezpublish.security.voter.core:
        class: eZ\Publish\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter
        arguments: ['@eZ\Publish\API\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.voter.value_object:
        class: eZ\Publish\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter
        arguments: ['@eZ\Publish\API\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.controller:
        public: true
        class: eZ\Publish\Core\MVC\Symfony\Controller\SecurityController
        arguments: ["@twig", "@ezpublish.config.resolver", "@security.authentication_utils"]

    ezpublish.security.login_listener:
        class: eZ\Publish\Core\MVC\Symfony\Security\EventListener\SecurityListener
        arguments:
            - '@eZ\Publish\API\Repository\PermissionResolver'
            - '@eZ\Publish\API\Repository\UserService'
            - "@ezpublish.config.resolver"
            - "@event_dispatcher"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "%fragment.path%"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.security.user_provider: '@ezpublish.security.user_provider.username'
